name: cube_workouts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  hive: ^2.2.3
  image_picker: ^1.2.1
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.11.1
  freezed: ^3.2.3
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
